name: Dice API Actions
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: read

jobs:
  run-lint:
    uses: lalugue/dice-api/.github/workflows/lint.yml@main
  run-tests:
    uses: lalugue/dice-api/.github/workflows/tests.yml@main
